In [22]:
import torch
import torch.nn as nn
from plot_lib import set_default, show_scatterplot, plot_bases
from matplotlib.pyplot import plot, title, axis
import numpy as np

In [23]:
import torch.nn.functional as F
from torch.autograd import Variable

In [24]:
a = np.array([[4,5,2,2,1],
[3,3,2,2,4],
[4,3,4,1,1],
[5,1,4,1,2],
[5,1,3,1,4]])

In [25]:
at = torch.from_numpy(a)

In [26]:
f = np.array([[4,3,3],[5,5,5],[2,4,3]])
ft = torch.from_numpy(f)

In [27]:
m = nn.Conv2d(1,1,3)
#m = nn.Conv2d(in_channels=5, out_channels=3, kernel_size=3, stride=1)

In [28]:
a1 = at.view(1,1,at.shape[0], at.shape[1])
a1d = a1.double()

In [29]:
f1 = ft.view(1,1,ft.shape[0], ft.shape[1])
f1d = f1.double()

In [30]:
out = F.conv2d(a1d, f1d)
print(out)

tensor([[[[109.,  92.,  72.],
          [108.,  85.,  74.],
          [110.,  74.,  79.]]]], dtype=torch.float64)


In [90]:
F.max_pool2d(out, 2, 1)

tensor([[[[109.,  92.],
          [110.,  85.]]]], dtype=torch.float64)

In [31]:
a1f = a1.float()  
m(a1f)

tensor([[[[-2.4122, -1.5076, -1.1445],
          [-2.3210, -2.1776, -0.7190],
          [-1.7687, -2.1418, -2.2009]]]], grad_fn=<MkldnnConvolutionBackward>)

In [91]:
a

array([[4, 5, 2, 2, 1],
       [3, 3, 2, 2, 4],
       [4, 3, 4, 1, 1],
       [5, 1, 4, 1, 2],
       [5, 1, 3, 1, 4]])

In [32]:
rotf = np.rot90(np.rot90(f))

In [72]:
rotf

array([[3, 4, 2],
       [5, 5, 5],
       [3, 3, 4]])

In [57]:
rotft = torch.from_numpy(rotf.copy())

In [58]:
rotft

tensor([[3, 4, 2],
        [5, 5, 5],
        [3, 3, 4]])

In [65]:
lt = torch.ones_like(out)
print(lt.shape)

torch.Size([1, 1, 3, 3])


In [67]:
lt

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], dtype=torch.float64)

In [61]:
rotft1 = rotft.view(1,1,rotft.shape[0], rotft.shape[1])
rotft1d = rotft1.double()

In [68]:
rotft1d

tensor([[[[3., 4., 2.],
          [5., 5., 5.],
          [3., 3., 4.]]]], dtype=torch.float64)

In [69]:
out2 = F.conv2d(lt, rotft1d)
print(out2)

tensor([[[[34.]]]], dtype=torch.float64)


In [33]:
from scipy import signal

In [41]:
l = np.ones(f.shape)

In [71]:
l

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
signal.convolve2d(l, f)

array([[ 4.,  7., 10.,  6.,  3.],
       [ 9., 17., 25., 16.,  8.],
       [11., 23., 34., 23., 11.],
       [ 7., 16., 24., 17.,  8.],
       [ 2.,  6.,  9.,  7.,  3.]])

In [76]:
m2 = nn.AvgPool2d(3, stride=2)

In [85]:
input = torch.ones(2, 6, 6)

In [86]:
output = m2(input)

In [87]:
print(input)
print(output)

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
