In [1]:
import torch
import torch.nn as nn
from plot_lib import set_default, show_scatterplot, plot_bases
from matplotlib.pyplot import plot, title, axis
import numpy as np

In [68]:
import torch.nn.functional as F
from torch.autograd import Variable

In [69]:
a = np.array([[4,5,2,2,1],
[3,3,2,2,4],
[4,3,4,1,1],
[5,1,4,1,2],
[5,1,3,1,4]])
a = a.astype(float)

In [70]:
a.shape

(5, 5)

In [80]:
at = torch.tensor(a, requires_grad=True)
at = at.view(1,1,at.shape[0], at.shape[1])
at = at.clone().detach().requires_grad_(True)
print(at)

tensor([[[[4., 5., 2., 2., 1.],
          [3., 3., 2., 2., 4.],
          [4., 3., 4., 1., 1.],
          [5., 1., 4., 1., 2.],
          [5., 1., 3., 1., 4.]]]], dtype=torch.float64, requires_grad=True)


In [81]:
f = np.array([[4,3,3],[5,5,5],[2,4,3]])
f = f.astype(float)
ft = torch.tensor(f, requires_grad=True)
ft = ft.view(1,1,ft.shape[0], ft.shape[1])
ft = ft.clone().detach().requires_grad_(True)
print(ft)

tensor([[[[4., 3., 3.],
          [5., 5., 5.],
          [2., 4., 3.]]]], dtype=torch.float64, requires_grad=True)


In [73]:
#m = nn.Conv2d(1,1,3)
#m = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3, stride=1)

In [82]:
out = F.conv2d(at, ft)
print(out)

tensor([[[[109.,  92.,  72.],
          [108.,  85.,  74.],
          [110.,  74.,  79.]]]], dtype=torch.float64,
       grad_fn=<ThnnConv2DBackward>)


In [83]:
gradients = torch.ones(3,3, dtype=torch.float64)
gradients = gradients.view(1,1,gradients.shape[0], gradients.shape[1])
gradients = gradients.clone().detach().requires_grad_(True)
print(gradients)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], dtype=torch.float64, requires_grad=True)


In [84]:
 out.backward(gradients)

In [85]:
print(at.grad)

tensor([[[[ 4.,  7., 10.,  6.,  3.],
          [ 9., 17., 25., 16.,  8.],
          [11., 23., 34., 23., 11.],
          [ 7., 16., 24., 17.,  8.],
          [ 2.,  6.,  9.,  7.,  3.]]]], dtype=torch.float64)


In [86]:
F.max_pool2d(out, 2, 1)

tensor([[[[109.,  92.],
          [110.,  85.]]]], dtype=torch.float64,
       grad_fn=<MaxPool2DWithIndicesBackward>)

In [12]:
a

array([[4, 5, 2, 2, 1],
       [3, 3, 2, 2, 4],
       [4, 3, 4, 1, 1],
       [5, 1, 4, 1, 2],
       [5, 1, 3, 1, 4]])

In [13]:
rotf = np.rot90(np.rot90(f))

In [14]:
rotf

array([[3, 4, 2],
       [5, 5, 5],
       [3, 3, 4]])

In [15]:
rotft = torch.from_numpy(rotf.copy())

In [16]:
rotft

tensor([[3, 4, 2],
        [5, 5, 5],
        [3, 3, 4]])

In [17]:
lt = torch.ones_like(out)
print(lt.shape)

torch.Size([1, 1, 3, 3])


In [18]:
lt

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], dtype=torch.float64)

In [19]:
rotft1 = rotft.view(1,1,rotft.shape[0], rotft.shape[1])
rotft1d = rotft1.double()

In [20]:
rotft1d

tensor([[[[3., 4., 2.],
          [5., 5., 5.],
          [3., 3., 4.]]]], dtype=torch.float64)

In [21]:
out2 = F.conv2d(lt, rotft1d)
print(out2)

tensor([[[[34.]]]], dtype=torch.float64)


In [22]:
from scipy import signal

In [23]:
l = np.ones(f.shape)

In [24]:
l

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
signal.convolve2d(l, f)

array([[ 4.,  7., 10.,  6.,  3.],
       [ 9., 17., 25., 16.,  8.],
       [11., 23., 34., 23., 11.],
       [ 7., 16., 24., 17.,  8.],
       [ 2.,  6.,  9.,  7.,  3.]])

In [26]:
m2 = nn.AvgPool2d(3, stride=2)

In [27]:
input = torch.ones(2, 6, 6)

In [28]:
output = m2(input)

In [29]:
print(input)
print(output)

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [34]:
ma = nn.AdaptiveMaxPool2d((2,2))
input = torch.randn(2, 4, 4,)
output = ma(input)
print(input)
print(output)

tensor([[[ 0.3233, -0.4814,  1.6139,  0.3389],
         [ 0.1395,  1.2904, -0.5291, -0.6258],
         [-0.4185, -1.5935, -1.2115,  0.5412],
         [-1.0757, -1.0937,  1.6516, -0.8540]],

        [[-0.2606,  0.1703,  0.8965,  0.5885],
         [ 0.8797, -2.5895,  1.6293, -0.1485],
         [-1.8853,  0.7779,  1.0013, -0.4320],
         [ 1.2135,  1.3260,  0.9249, -1.8527]]])
tensor([[[ 1.2904,  1.6139],
         [-0.4185,  1.6516]],

        [[ 0.8797,  1.6293],
         [ 1.3260,  1.0013]]])
